version: '3.1'

services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scms
    ports:
      - "2345:5432"
    volumes:
      - ./dc_volumes/postgres:/var/lib/postgresql/data
